name: 音频影像
description: 本目录收录了与跨性别相关的音频影像作品，包括艺术中心与国际美术馆合作的项目。这些作品展示了跨性别艺术家的创作，反映了其独特的视角和经历。
curator: ''
source: ''
tags:
- 跨性别艺术
- 音频影像
- 创作表达
- 金杜艺术中心
- 伦敦白教堂美术馆
license: ''
files:
- name: 2019年9月24日_温哥华主校_放映电影《为什么我喜欢做酷儿仔》
  filename: 2019年9月24日_温哥华主校_放映电影《为什么我喜欢做酷儿仔》.pdf
  type: document
  format: PDF Document
  size: 348768
  md5: 51bb113e428b28c840e407803b55a494
  page: 2019年9月24日_温哥华主校_放映电影《为什么我喜欢做酷儿仔》_page.md
- name: 2021年Bubble_T亚裔酷儿派对报道
  filename: 2021年Bubble_T亚裔酷儿派对报道.pdf
  type: document
  format: PDF Document
  size: 2199995
  md5: e97a6830e70e550b56f10825bac6fe6c
  page: 2021年Bubble_T亚裔酷儿派对报道_page.md
- name: PDF_金杜艺术中心x_伦敦白教堂美术馆国际艺术家电影AFI
  filename: PDF_金杜艺术中心x_伦敦白教堂美术馆国际艺术家电影AFI.pdf
  type: document
  format: PDF Document
  size: 155231
  md5: 8a36718491d2cf5154757c137db53b8f
  page: PDF_金杜艺术中心x_伦敦白教堂美术馆国际艺术家电影AFI_page.md
- name: 上海骄傲电影节_活动策划与影片介绍_马修·拜伦与李佳桓
  filename: 上海骄傲电影节_活动策划与影片介绍_马修·拜伦与李佳桓.pdf
  type: document
  format: PDF Document
  size: 2320650
  md5: 033e9f3e97d5766891db97e5d18102fb
  page: 上海骄傲电影节_活动策划与影片介绍_马修·拜伦与李佳桓_page.md
- name: 年度无限酷儿时装秀创始人阿雅娜·雅尼·布鲁姆菲尔德访谈
  filename: 年度无限酷儿时装秀创始人阿雅娜·雅尼·布鲁姆菲尔德访谈.pdf
  type: document
  format: PDF Document
  size: 199753
  md5: 37816894e182495a45f706a9f956645e
  page: 年度无限酷儿时装秀创始人阿雅娜·雅尼·布鲁姆菲尔德访谈_page.md
subdirs:
- 限制级内容
