name: 社群及NGO文件
description: 本部分可收录的内容较为广泛。无论是如北京同志中心、同语这样的 NGO 出具的调查报告、教程指南，还是跨儿社群某论坛上由志愿者写作的 HRT
  指南、出柜指南等，甚至是涉及色情内容的「女装」或自我探索类教程，均可收录在本版块内。这一目录也包括各类医疗体系、学校和社群的相关资料。这些信息有助于了解支持跨性别人士的组织资源及环境。
curator: ''
source: ''
tags:
- 跨性别
- 社群
- NGO
- 医疗资源
- 教育
- 组织
license: ''
files: []
subdirs:
- 其他组织文件
- 医院和医疗体系
- 学校
- 手册指南
- 社群讨论
- 统计报告
