name: 学校
description: 该目录包含与学校及教育相关的跨性别社群和非政府组织的文件。这些文件可能涵盖学校内的支持资源、跨性别学生的权益保护信息、教育政策的变革等内容，以推动对跨性别群体的理解和接纳。
curator: ''
source: ''
tags:
- 跨性别
- 学校
- 教育
- 社群支持
- 权益保护
- 非政府组织
license: ''
files:
- name: PDF_Cover_Page_校长致辞作为学校的家人保持联系_-_Mason_Families
  filename: PDF_Cover_Page_校长致辞作为学校的家人保持联系_-_Mason_Families.pdf
  type: document
  format: PDF Document
  size: 480609
  md5: c2a69090565682804492ec11db83bbb8
  page: PDF_Cover_Page_校长致辞作为学校的家人保持联系_-_Mason_Families_page.md
- name: PDF_LGBTQ_青少年资源_-_Fairfax_County_Public_Schools
  filename: PDF_LGBTQ_青少年资源_-_Fairfax_County_Public_Schools.pdf
  type: document
  format: PDF Document
  size: 919533
  md5: 6195c9709db3fe042c92bd288b802852
  page: PDF_LGBTQ_青少年资源_-_Fairfax_County_Public_Schools_page.md
- name: PDF_STUDENT_-_SECURE_-_cdninternationalstudentcom
  filename: PDF_STUDENT_-_SECURE_-_cdninternationalstudentcom.pdf
  type: document
  format: PDF Document
  size: 7344036
  md5: 744d81f1ace4d456e6f00672a7bdb899
  page: PDF_STUDENT_-_SECURE_-_cdninternationalstudentcom_page.md
- name: PDF_主題變性學生支持指南_關鍵術語定義_-_Hawaii_DOE
  filename: PDF_主題變性學生支持指南_關鍵術語定義_-_Hawaii_DOE.pdf
  type: document
  format: PDF Document
  size: 809305
  md5: 7eb2f2937211c5582210bbb013f0a004
  page: PDF_主題變性學生支持指南_關鍵術語定義_-_Hawaii_DOE_page.md
- name: PDF_協助同志與多元性別兒童及青少年建立健康未來的家人接纳计划海报_sfsu.edu
  filename: PDF_協助同志與多元性別兒童及青少年建立健康未來的家人接纳计划海报_sfsu.edu.pdf
  type: document
  format: PDF Document
  size: 913955
  md5: d6638f09aa2db08b3bca539498e482e8
  page: PDF_協助同志與多元性別兒童及青少年建立健康未來的家人接纳计划海报_sfsu.edu_page.md
- name: PDF_厦门大学学生医疗保险手册
  filename: PDF_厦门大学学生医疗保险手册.pdf
  type: document
  format: PDF Document
  size: 622490
  md5: 1d27f4981581016f65b00b973cd775f9
  page: PDF_厦门大学学生医疗保险手册_page.md
- name: PDF_国立大学咨询辅导中心
  filename: PDF_国立大学咨询辅导中心.pdf
  type: document
  format: PDF Document
  size: 381766
  md5: ac5f3072c00293ede5b0d89223093b0d
  page: PDF_国立大学咨询辅导中心_page.md
- name: PDF_心理健康资源_portland_public_schools
  filename: PDF_心理健康资源_portland_public_schools.pdf
  type: document
  format: PDF Document
  size: 192594
  md5: 925d0e861a4d73ec97e8ea7f59e1f91c
  page: PDF_心理健康资源_portland_public_schools_page.md
- name: PDF_性別手冊學生版
  filename: PDF_性別手冊學生版.pdf
  type: document
  format: PDF Document
  size: 1892171
  md5: 3d35872f6a9866a9a2428feae63fed02
  page: PDF_性別手冊學生版_page.md
- name: PDF_性取向和性别认同
  filename: PDF_性取向和性别认同.pdf
  type: document
  format: PDF Document
  size: 239282
  md5: 053b0408141f9bb871b7f733cdea3a03
  page: PDF_性取向和性别认同_page.md
- name: PDF_性取向和性别认同SOGI_给家长和监护人的信息__SOGI_包容性教育
  filename: PDF_性取向和性别认同SOGI_给家长和监护人的信息__SOGI_包容性教育.pdf
  type: document
  format: PDF Document
  size: 2006092
  md5: e0290f3959e7f9e0ebcdc80dcc8cf691
  page: PDF_性取向和性别认同SOGI_给家长和监护人的信息__SOGI_包容性教育_page.md
- name: PDF_教育工作者看如何關顧跨性別人士
  filename: PDF_教育工作者看如何關顧跨性別人士.pdf
  type: document
  format: PDF Document
  size: 8363
  md5: d9cef1ab6f4f6305fa1bcf867b861d69
  page: PDF_教育工作者看如何關顧跨性別人士_page.md
- name: PDF_费郡家庭生活教育
  filename: PDF_费郡家庭生活教育.pdf
  type: document
  format: PDF Document
  size: 181997
  md5: 47d7bf82e8b3f9568a1dc3300df9be98
  page: PDF_费郡家庭生活教育_page.md
- name: 主题变性学生支持指南_关键术语定义
  filename: 主题变性学生支持指南_关键术语定义.pdf
  type: document
  format: PDF Document
  size: 498569
  md5: a464ec18c1accf51de0c9c5fc4105fe6
  page: 主题变性学生支持指南_关键术语定义_page.md
- name: 密歇根州立大学禁止歧视反骚扰和禁止报复通知
  filename: 密歇根州立大学禁止歧视反骚扰和禁止报复通知.pdf
  type: document
  format: PDF Document
  size: 389463
  md5: 20d530f40aad3960d35876e5d6b85379
  page: 密歇根州立大学禁止歧视反骚扰和禁止报复通知_page.md
- name: 康涅狄格大学_包括性骚扰和基于性别的骚扰性侵犯性剥削亲密伴侣暴力政策
  filename: 康涅狄格大学_包括性骚扰和基于性别的骚扰性侵犯性剥削亲密伴侣暴力政策.pdf
  type: document
  format: PDF Document
  size: 494583
  md5: 967617158340d91367ddcb6cecf382ca
  page: 康涅狄格大学_包括性骚扰和基于性别的骚扰性侵犯性剥削亲密伴侣暴力政策_page.md
- name: 性别手册学生版
  filename: 性别手册学生版.pdf
  type: document
  format: PDF Document
  size: 1899545
  md5: 9c332aeeea91f9cd0ce700c1f1132f08
  page: 性别手册学生版_page.md
- name: 性别手册教职员工版关怀和应对_中央大学多元化中心
  filename: 性别手册教职员工版关怀和应对_中央大学多元化中心.pdf
  type: document
  format: PDF Document
  size: 1718066
  md5: 3d420749d25335c4e728e5979fb637e5
  page: 性别手册教职员工版关怀和应对_中央大学多元化中心_page.md
- name: 跨性別和性別多樣化青少年父母和照顧者的
  filename: 跨性別和性別多樣化青少年父母和照顧者的.pdf
  type: document
  format: PDF Document
  size: 716035
  md5: db54e32bc598bedeb9c55de600bad28a
  page: 跨性別和性別多樣化青少年父母和照顧者的_page.md
- name: 青少年面对COVID__(LGBTQIA)_健康和心理健康资源_NYC
  filename: 青少年面对COVID__(LGBTQIA)_健康和心理健康资源_NYC.pdf
  type: document
  format: PDF Document
  size: 303623
  md5: e0d60dd869d64f2a3a00b194da070146
  page: 青少年面对COVID__(LGBTQIA)_健康和心理健康资源_NYC_page.md
subdirs: []
