name: 文学作品和艺术创作
description: 本部分收录一切形式的跨儿文学艺术创作。无论是发布于互联网某个阴暗角落的「变性人」自传，还是形式晦涩、发人深省的诗歌电影，均可收录在本版块。，涵盖了多种形式的表达，包括小说、漫画、纪实作品、自传和诗歌等。
curator: ''
source: ''
tags:
- 跨性别
- 文学作品
- 艺术创作
- 自传
- 小说
- 漫画
- 纪实作品
- 诗歌
license: ''
files: []
subdirs:
- 图像
- 小说
- 漫画
- 纪实作品
- 自传
- 诗歌
- 音频影像
