name: 伪声
description: 本目录‘伪声’集中在跨性别女性（MTF）声音的女性化及其教学资源。目录中包含了多份有关如何调整和改善声音的手册与指南。这些资料为跨性别女性提供了关于声音女性化的具体方法和实践技巧，帮助她们在转变过程中更自信地表达自己的性别身份。‘MTF声音女性化手册’详细介绍了发音技巧、语调调整以及如何在讲话时营造女性化的声音特质；‘伪声基础整理以及教学’则提供了一些基本练习和建议，适合初学者使用；而‘成为女孩子的声音’则探讨了在声音女性化过程中可能遇到的心理与情感挑战，鼓励跨性别女性积极面对这些变化。整体来看，这个目录为希望进行声音女性化的跨性别者提供了宝贵的实用信息和经验分享，是一个重要的资源集合。
curator: ''
source: ''
tags:
- 声音女性化
- 跨性别
- MTF
- 声音训练
- 性别认同
- 教育资源
- 社群支持
- 生存经验
license: ''
files:
- name: MTF声音女性化手册
  filename: MTF声音女性化手册.pdf
  type: document
  format: PDF Document
  size: 1661302
  md5: ec92a49e2a32626b918591a35121af00
  page: MTF声音女性化手册_page.md
- name: 伪声基础整理以及教学
  filename: 伪声基础整理以及教学.pptx
  type: other
  format: Unknown Format
  size: 72170
  md5: 6bad8b9276f5e7f8fb9af6f371a4bd59
  page: 伪声基础整理以及教学.pptx
subdirs:
- 成为女孩子的声音
