name: 杂志及新闻报道
description: 本目录包含关于中国大陆、海外及港澳台地区的跨性别相关杂志与新闻报道，二级分类按照发布的报纸杂志所在地区区分。旨在汇集各地对跨性别话题的不同视角与声音，提供相关信息和资源。此处主要收集传统媒体以及 PDF 文档或图片形式的新闻报道，例如杂志、剪报等。网页新闻报道请访问 <https://news.transchinese.org>，包含数千个相关网页。
curator: ''
source: ''
tags:
- 跨性别
- 杂志
- 新闻报道
- 生命故事
- 社会环境
license: ''
files: []
subdirs:
- 中国大陆
- 海外
- 港澳台
