name: 纪实作品
description: 该目录收录与跨性别相关的纪实作品，展现跨性别者的真实生活与经历。这些作品不仅反映了个人故事，还呈现了对于社会现象的深刻洞察，包括对身份认同、过渡过程及社会接受度等话题的探索。
curator: ''
source: ''
tags:
- 跨性别
- 纪实文学
- 社会现象
- 身份认同
- 真实故事
license: ''
files:
- name: 2022-02-05_马骋Yura_酷儿女性看爱情与百合文化解构异性恋关系
  filename: 2022-02-05_马骋Yura_酷儿女性看爱情与百合文化解构异性恋关系.pdf
  type: document
  format: PDF Document
  size: 2647680
  md5: 2ebe45d184bec02dd67ce52561a507f3
  page: 2022-02-05_马骋Yura_酷儿女性看爱情与百合文化解构异性恋关系_page.md
- name: KS_故事-_克氏综合征
  filename: KS_故事-_克氏综合征.pdf
  type: document
  format: PDF Document
  size: 1145392
  md5: 18b1dc0f000f562fccaf410f67e83e22
  page: KS_故事-_克氏综合征_page.md
- name: Les+双月刊_2007年5月_果米的苦乐生活
  filename: Les+双月刊_2007年5月_果米的苦乐生活.pdf
  type: document
  format: PDF Document
  size: 2669249
  md5: 93a9cdffdc1c4802342b3fbb67b436b5
  page: Les+双月刊_2007年5月_果米的苦乐生活_page.md
- name: PDF_專訪雙性人細細老師
  filename: PDF_專訪雙性人細細老師.pdf
  type: document
  format: PDF Document
  size: 554776
  md5: 55089d0cdd170e7959cf5b9dbcb0ed08
  page: PDF_專訪雙性人細細老師_page.md
- name: PDF_酷儿城市在中国_电影人专访
  filename: PDF_酷儿城市在中国_电影人专访.pdf
  type: document
  format: PDF Document
  size: 468004
  md5: ec993b41550682b29cbe188904f59664
  page: PDF_酷儿城市在中国_电影人专访_page.md
- name: PDF_醫生說是陰莖其實是一條肉_專訪雙性人細細老師
  filename: PDF_醫生說是陰莖其實是一條肉_專訪雙性人細細老師.pdf
  type: document
  format: PDF Document
  size: 567748
  md5: 9df569a27589ae634a59e114fcbd8237
  page: PDF_醫生說是陰莖其實是一條肉_專訪雙性人細細老師_page.md
- name: 《守望初心》余艳长篇报告文学
  filename: 《守望初心》余艳长篇报告文学.pdf
  type: document
  format: PDF Document
  size: 765713
  md5: b56fad3d3c178e957bacb18f3d819324
  page: 《守望初心》余艳长篇报告文学_page.md
- name: 一个变性手术专家的手记
  filename: 一个变性手术专家的手记.pdf
  type: document
  format: PDF Document
  size: 1534779
  md5: 8b3f3bf112a5c23df62bc36a0103d48f
  page: 一个变性手术专家的手记_page.md
- name: 一个变性手术专家的手记_何清濂
  filename: 一个变性手术专家的手记_何清濂.pdf
  type: document
  format: PDF Document
  size: 1298862
  md5: efdd890ac10ac2102593014f41a3d771
  page: 一个变性手术专家的手记_何清濂_page.md
- name: 一个精神病医生的手记_-_钟健夫_-_1992
  filename: 一个精神病医生的手记_-_钟健夫_-_1992.pdf
  type: document
  format: PDF Document
  size: 3247048
  md5: e0990999df17b7b377eba468eb5acfa2
  page: 一个精神病医生的手记_-_钟健夫_-_1992_page.md
- name: 中国“变性人”现象_方刚_1996_广州出版社
  filename: 中国“变性人”现象_方刚_1996_广州出版社.pdf
  type: document
  format: PDF Document
  size: 12613192
  md5: b816af5959f12bb4e786ef2cbc9b0da8
  page: 中国“变性人”现象_方刚_1996_广州出版社_page.md
- name: 今后的路并不平坦——记“变性人”邹丹妮_王莉
  filename: 今后的路并不平坦——记“变性人”邹丹妮_王莉.pdf
  type: document
  format: PDF Document
  size: 644943
  md5: 6e614b08e2bdd54af5c046256b8c7161
  page: 今后的路并不平坦——记“变性人”邹丹妮_王莉_page.md
- name: 从一个变性人的痛苦说起……_储兆瑞
  filename: 从一个变性人的痛苦说起……_储兆瑞.pdf
  type: document
  format: PDF Document
  size: 1359629
  md5: 99e725a1da9a00f10a3c826e95c0259c
  page: 从一个变性人的痛苦说起……_储兆瑞_page.md
- name: 变性人生活辛酸
  filename: 变性人生活辛酸.pdf
  type: document
  format: PDF Document
  size: 143480
  md5: 608cf0e40e3ccff01a4f56b18d73c8fe
  page: 变性人生活辛酸_page.md
- name: 同聲同氣_香港年長女同志口述史_鄧芝珊_伍詠欣Chinese_手民出版社
  filename: 同聲同氣_香港年長女同志口述史_鄧芝珊_伍詠欣Chinese_手民出版社.pdf
  type: document
  format: PDF Document
  size: 34999911
  md5: fb8b70df0dc26d2c5688e4c98f873874
  page: 同聲同氣_香港年長女同志口述史_鄧芝珊_伍詠欣Chinese_手民出版社_page.md
- name: 坪上村传_彭东明_2021年1月22日
  filename: 坪上村传_彭东明_2021年1月22日.pdf
  type: document
  format: PDF Document
  size: 1984203
  md5: c54952c7e22251def0b43658513ac024
  page: 坪上村传_彭东明_2021年1月22日_page.md
- name: 姜昆与我巧遇变性人_吴钢
  filename: 姜昆与我巧遇变性人_吴钢.pdf
  type: document
  format: PDF Document
  size: 310036
  md5: 29e01be09fa6aa77479ef1611ad741aa
  page: 姜昆与我巧遇变性人_吴钢_page.md
- name: 我的性别我做主_夏日艳阳
  filename: 我的性别我做主_夏日艳阳.pdf
  type: document
  format: PDF Document
  size: 482621
  md5: 7796cd478efa73c186390aaf18a44540
  page: 我的性别我做主_夏日艳阳_page.md
- name: 捕捉香港酷儿地景中的女性访谈_马兰清著
  filename: 捕捉香港酷儿地景中的女性访谈_马兰清著.pdf
  type: document
  format: PDF Document
  size: 1030495
  md5: 8ea505f412f4bc1b983350ef99e99097
  page: 捕捉香港酷儿地景中的女性访谈_马兰清著_page.md
- name: 潘柏林,_刘烨,_韩萌,_陈冰锐_走出性别困境：“跨性别”与“性别焦虑”的医疗援助_上海科学技术文献出版社_2023
  filename: 潘柏林,_刘烨,_韩萌,_陈冰锐_走出性别困境：“跨性别”与“性别焦虑”的医疗援助_上海科学技术文献出版社_2023.pdf
  type: document
  format: PDF Document
  size: 7095388
  md5: 83c4b0e4de440789160d6e6f0149bf49
  page: 潘柏林,_刘烨,_韩萌,_陈冰锐_走出性别困境：“跨性别”与“性别焦虑”的医疗援助_上海科学技术文献出版社_2023_page.md
- name: 生命故事与现代社会探讨_书季_张小娜_2009
  filename: 生命故事与现代社会探讨_书季_张小娜_2009.pdf
  type: document
  format: PDF Document
  size: 673006
  md5: d1838b4d2e0ad1d8728b7904109d5950
  page: 生命故事与现代社会探讨_书季_张小娜_2009_page.md
- name: 秦惠英，你在哪里？_方刚
  filename: 秦惠英，你在哪里？_方刚.pdf
  type: document
  format: PDF Document
  size: 454618
  md5: 6852615ed39f779f9ddb314ba9e00919
  page: 秦惠英，你在哪里？_方刚_page.md
- name: 纠正上帝的错误_“中国变性手术之父”何清濂的非常记忆_吴兴人_2005_上海文艺出版社
  filename: 纠正上帝的错误_“中国变性手术之父”何清濂的非常记忆_吴兴人_2005_上海文艺出版社.pdf
  type: document
  format: PDF Document
  size: 20567667
  md5: 9f2dff3fcef6c06febe0c8b1e68a91d6
  page: 纠正上帝的错误_“中国变性手术之父”何清濂的非常记忆_吴兴人_2005_上海文艺出版社_page.md
- name: 蝶变_一个变性丽人的心灵纪实_隋易_1998_内蒙古人民出版社
  filename: 蝶变_一个变性丽人的心灵纪实_隋易_1998_内蒙古人民出版社.pdf
  type: document
  format: PDF Document
  size: 20150817
  md5: a0b951e49282cb65a28099ead6ce1fe1
  page: 蝶变_一个变性丽人的心灵纪实_隋易_1998_内蒙古人民出版社_page.md
- name: 跨越兩代的性別鴻溝
  filename: 跨越兩代的性別鴻溝.pdf
  type: document
  format: PDF Document
  size: 1399268
  md5: 28fd445ed49d40c4d43e0bc0a0c09115
  page: 跨越兩代的性別鴻溝_page.md
- name: 阴阳大裂变——变性人的故事_杨昆_健康生活_2002
  filename: 阴阳大裂变——变性人的故事_杨昆_健康生活_2002.pdf
  type: document
  format: PDF Document
  size: 508880
  md5: 0729a800a9eae6fff87d0189e3c0b907
  page: 阴阳大裂变——变性人的故事_杨昆_健康生活_2002_page.md
subdirs: []
