name: 资料指南
description: 该目录包含跨性别相关的非政府组织（NGO）资料指南，旨在为社区成员提供资源和支持，帮助他们了解可用的服务与信息。
curator: ''
source: ''
tags:
- 跨性别
- 非政府组织
- 资料指南
- 社区支持
license: ''
files:
- name: 2022版跨性别医疗照护手册
  filename: 2022版跨性别医疗照护手册.pdf
  type: document
  format: PDF Document
  size: 103556788
  md5: 275eaa772f9aa521cfc5922cf5921cb0
  page: 2022版跨性别医疗照护手册_page.md
- name: Gossip_Boys_and_Girls_-_跨性別資源中心
  filename: Gossip_Boys_and_Girls_-_跨性別資源中心.pdf
  type: document
  format: PDF Document
  size: 1115812
  md5: d923789a408343044c2257fe71386556
  page: Gossip_Boys_and_Girls_-_跨性別資源中心_page.md
- name: PDF_BSA_指南有关性别认同问题的投诉
  filename: PDF_BSA_指南有关性别认同问题的投诉.pdf
  type: document
  format: PDF Document
  size: 462804
  md5: e8e303221067e34882318b40c41ea328
  page: PDF_BSA_指南有关性别认同问题的投诉_page.md
- name: PDF_数字暴力报道提示单记者和媒体的实用参考指南
  filename: PDF_数字暴力报道提示单记者和媒体的实用参考指南.pdf
  type: document
  format: PDF Document
  size: 5413921
  md5: 2e750333655956f7fa40c08a56188550
  page: PDF_数字暴力报道提示单记者和媒体的实用参考指南_page.md
- name: PDF_社群指南_性少数性工作者经历的恐同与恐跨性别
  filename: PDF_社群指南_性少数性工作者经历的恐同与恐跨性别.pdf
  type: document
  format: PDF Document
  size: 1170374
  md5: 95612521202218e4ef57e8256f7895dc
  page: PDF_社群指南_性少数性工作者经历的恐同与恐跨性别_page.md
- name: PDF_跨性别_反暴力_手册_跨青年教育中心
  filename: PDF_跨性别_反暴力_手册_跨青年教育中心.pdf
  type: document
  format: PDF Document
  size: 6866382
  md5: 7284c6a5cb1d463be6ee29dad6cc7139
  page: PDF_跨性别_反暴力_手册_跨青年教育中心_page.md
- name: SG出柜指南_去风险删减版
  filename: SG出柜指南_去风险删减版.pdf
  type: document
  format: PDF Document
  size: 18701734
  md5: 4227a50527ff344e76700e2c0b5ecc55
  page: SG出柜指南_去风险删减版_page.md
- name: WPATH_SOC_V7
  filename: WPATH_SOC_V7.pdf
  type: document
  format: PDF Document
  size: 5523764
  md5: b9ed2f347e493da7dd9c2c4fb4040ee5
  page: WPATH_SOC_V7_page.md
- name: q-a-for-parents-family-of-transgender-2011-simplified-chinese
  filename: q-a-for-parents-family-of-transgender-2011-simplified-chinese.pdf
  type: document
  format: PDF Document
  size: 2292264
  md5: e9be2c03c19045694b75d77cf720decc
  page: q-a-for-parents-family-of-transgender-2011-simplified-chinese_page.md
- name: 《跨性别者购药反诈防骗指南_V2.0》
  filename: 《跨性别者购药反诈防骗指南_V2.0》.pdf
  type: document
  format: PDF Document
  size: 834506
  md5: 7de22901869deee53723ff35ecc01216
  page: 《跨性别者购药反诈防骗指南_V2.0》_page.md
- name: 中国跨性别出柜指南
  filename: 中国跨性别出柜指南.pdf
  type: document
  format: PDF Document
  size: 647858
  md5: 6b8bf6d9f0fcda0990195b7f86dc05fe
  page: 中国跨性别出柜指南_page.md
- name: 亚太跨性别健康蓝图
  filename: 亚太跨性别健康蓝图.pdf
  type: document
  format: PDF Document
  size: 8426774
  md5: 5002f5c2aecaa65677aee4a65ec3326a
  page: 亚太跨性别健康蓝图_page.md
- name: 伴您同行_专为跨性别儿童的父母准备的指南(SG出柜指南_原版)
  filename: 伴您同行_专为跨性别儿童的父母准备的指南(SG出柜指南_原版).pdf
  type: document
  format: PDF Document
  size: 18705720
  md5: b35dcebc987983a703784091f2914fa6
  page: 伴您同行_专为跨性别儿童的父母准备的指南(SG出柜指南_原版)_page.md
- name: 关于跨性别者和性别非二元_人群的初级和性别肯定护理_指南_UCSF
  filename: 关于跨性别者和性别非二元_人群的初级和性别肯定护理_指南_UCSF.pdf
  type: document
  format: PDF Document
  size: 2805105
  md5: b554645b8db93ce1555d79da01860e60
  page: 关于跨性别者和性别非二元_人群的初级和性别肯定护理_指南_UCSF_page.md
- name: 北同跨性别医疗照护手册
  filename: 北同跨性别医疗照护手册.pdf
  type: document
  format: PDF Document
  size: 14257055
  md5: 7b341a89b6f1a00c440f113844b336b9
  page: 北同跨性别医疗照护手册_page.md
- name: 幫助家裡有同志_（女同性戀、男同性戀、雙性戀、跨性別）成員的家庭指南
  filename: 幫助家裡有同志_（女同性戀、男同性戀、雙性戀、跨性別）成員的家庭指南.pdf
  type: document
  format: PDF Document
  size: 6214131
  md5: eb996f2369ce39d533cfdc5793ca690a
  page: 幫助家裡有同志_（女同性戀、男同性戀、雙性戀、跨性別）成員的家庭指南_page.md
- name: 应对扭转治疗手册
  filename: 应对扭转治疗手册.pdf
  type: document
  format: PDF Document
  size: 1436635
  md5: df49d0a676cee9f83254c56b80be856f
  page: 应对扭转治疗手册_page.md
- name: 应对扭转治疗手册_-_同志亦凡人
  filename: 应对扭转治疗手册_-_同志亦凡人.pdf
  type: document
  format: PDF Document
  size: 1426230
  md5: 18e4384fe6f8659fa54c4f32a45339a8
  page: 应对扭转治疗手册_-_同志亦凡人_page.md
- name: 性侵害幸存者自助手册2.0
  filename: 性侵害幸存者自助手册2.0.pdf
  type: document
  format: PDF Document
  size: 627276
  md5: 7acea747293f919d220691cf2c9ed24d
  page: 性侵害幸存者自助手册2.0_page.md
- name: 我的跨性别孩子-_父母手册上册
  filename: 我的跨性别孩子-_父母手册上册.pdf
  type: document
  format: PDF Document
  size: 729676
  md5: 2359bff10c0e5231f94011918d3e0532
  page: 我的跨性别孩子-_父母手册上册_page.md
- name: 支持新西兰的彩虹人群性少数人群：精神心理健康专业_人员实用指南
  filename: 支持新西兰的彩虹人群性少数人群：精神心理健康专业_人员实用指南.pdf
  type: document
  format: PDF Document
  size: 769032
  md5: bf8df438fc6e70b09c5bf5545adde212
  page: 支持新西兰的彩虹人群性少数人群：精神心理健康专业_人员实用指南_page.md
- name: 是非男女-1
  filename: 是非男女-1.pdf
  type: document
  format: PDF Document
  size: 876373
  md5: 9b0b29c91143b41a8a3f05b99065ce22
  page: 是非男女-1_page.md
- name: 是非男女-2
  filename: 是非男女-2.pdf
  type: document
  format: PDF Document
  size: 771747
  md5: f280c3db4f5e293f61293a0210398734
  page: 是非男女-2_page.md
- name: 是非男女-3
  filename: 是非男女-3.pdf
  type: document
  format: PDF Document
  size: 570555
  md5: 134e0e139794cc48c7f4a1bc0f7ce6c1
  page: 是非男女-3_page.md
- name: 智同跨性别性健康手册2022年第一版
  filename: 智同跨性别性健康手册2022年第一版.pdf
  type: document
  format: PDF Document
  size: 6805837
  md5: c070d28c25a9868e51d131f690eddbbc
  page: 智同跨性别性健康手册2022年第一版_page.md
- name: 泰国手术指导
  filename: 泰国手术指导.pdf
  type: document
  format: PDF Document
  size: 214124
  md5: d4d9dbdc8eb4f5dc0f04143daebe0afc
  page: 泰国手术指导_page.md
- name: 自切教程萱酱版
  filename: 自切教程萱酱版.doc
  type: document
  format: Microsoft Word Document
  size: 2834944
  md5: b3b99eef3b83e7bb214b8bbaec7545fb
  page: 自切教程萱酱版_page.md
- name: 跨儿的性别困惑与身份认同
  filename: 跨儿的性别困惑与身份认同.pdf
  type: document
  format: PDF Document
  size: 990722
  md5: 9498199baf08bd94e78e8c8b31e4d02a
  page: 跨儿的性别困惑与身份认同_page.md
- name: 跨性別社福醫護手冊
  filename: 跨性別社福醫護手冊.pdf
  type: document
  format: PDF Document
  size: 14213949
  md5: e82c48e0b280daf977bb35d8e9e87610
  page: 跨性別社福醫護手冊_page.md
- name: 跨性別者自助手冊
  filename: 跨性別者自助手冊.pdf
  type: document
  format: PDF Document
  size: 22697773
  md5: 4b2fd72a89a8d9632e751d2782d96f65
  page: 跨性別者自助手冊_page.md
- name: 跨性别ABC
  filename: 跨性别ABC.pdf
  type: document
  format: PDF Document
  size: 246245
  md5: c9e07979861e9184cde04f07f5c9bd6d
  page: 跨性别ABC_page.md
- name: 跨性别_如何安全注射激素
  filename: 跨性别_如何安全注射激素.pdf
  type: document
  format: PDF Document
  size: 550989
  md5: 3dc2badf6ee46b6b60d6a5d7dd00657b
  page: 跨性别_如何安全注射激素_page.md
- name: 跨性别出柜手册
  filename: 跨性别出柜手册.pdf
  type: document
  format: PDF Document
  size: 161413
  md5: b8593f61a5458408ac369dd83b33bd0e
  page: 跨性别出柜手册_page.md
- name: 跨性别和多元性别人群健康照护指南（第八版)
  filename: 跨性别和多元性别人群健康照护指南（第八版).pdf
  type: document
  format: PDF Document
  size: 3738717
  md5: 168fc7b79987574bdd192280702eaa32
  page: 跨性别和多元性别人群健康照护指南（第八版)_page.md
- name: 跨性别安全指南
  filename: 跨性别安全指南.pdf
  type: document
  format: PDF Document
  size: 1665453
  md5: b04710ff9e2b7ae6c2300c8f87c34460
  page: 跨性别安全指南_page.md
- name: 跨性别证件修改手册
  filename: 跨性别证件修改手册.pdf
  type: document
  format: PDF Document
  size: 10046170
  md5: 88fa0af4a97084f72f3693b8a8bedeb0
  page: 跨性别证件修改手册_page.md
- name: 针对戒网瘾学校非法绑架未成年人的逃生方法解析
  filename: 针对戒网瘾学校非法绑架未成年人的逃生方法解析.pdf
  type: document
  format: PDF Document
  size: 1655083
  md5: d5353b9094b1a5c38be45db573f1bb11
  page: 针对戒网瘾学校非法绑架未成年人的逃生方法解析_page.md
- name: 青少年'性与生殖健康咨询技能手册
  filename: 青少年'性与生殖健康咨询技能手册.pdf
  type: document
  format: PDF Document
  size: 3592983
  md5: f715c657273b46eabf5d9a819160099e
  page: 青少年'性与生殖健康咨询技能手册_page.md
subdirs:
- 雌二醇凝胶自制方法
