name: 港澳台
description: 该目录收录了关于港澳台地区政府及官方组织发布的与跨性别相关的文件和信息，涉及相关政策、法律和社会环境的内容。这些文件旨在提供更清晰的法律框架和社会支持，以促进跨性别群体的权益。
curator: ''
source: ''
tags:
- 政府文件
- 港澳台
- 跨性别
- 法律政策
- 社会环境
license: ''
files:
- name: 1997_關注婦女性暴力協會_性別承認諮詢意見書
  filename: 1997_關注婦女性暴力協會_性別承認諮詢意見書.pdf
  type: document
  format: PDF Document
  size: 2086783
  md5: aebcccd72f55aa1d6f24b3ddc28d3298
  page: 1997_關注婦女性暴力協會_性別承認諮詢意見書_page.md
- name: 2014年婚姻修訂條例草案公聽會關於變性手術的意見摘要
  filename: 2014年婚姻修訂條例草案公聽會關於變性手術的意見摘要.pdf
  type: document
  format: PDF Document
  size: 1178754
  md5: f8064eae0c26a636e4bbde1138e40927
  page: 2014年婚姻修訂條例草案公聽會關於變性手術的意見摘要_page.md
- name: 2024_全國大專校院運動會_跨性別學生運動員參與政策
  filename: 2024_全國大專校院運動會_跨性別學生運動員參與政策.pdf
  type: document
  format: PDF Document
  size: 250092
  md5: f359d900a01d6fbcf25b0697d0594571
  page: 2024_全國大專校院運動會_跨性別學生運動員參與政策_page.md
- name: LGBTQIA性少数族群+咨询代表会问答_警察改革工作组
  filename: LGBTQIA性少数族群+咨询代表会问答_警察改革工作组.pdf
  type: document
  format: PDF Document
  size: 311790
  md5: 412f78fbe86075da80195395464b0d83
  page: LGBTQIA性少数族群+咨询代表会问答_警察改革工作组_page.md
- name: PDF_5_性別不安有甚麼治療方法_-_醫院管理局
  filename: PDF_5_性別不安有甚麼治療方法_-_醫院管理局.pdf
  type: document
  format: PDF Document
  size: 959835
  md5: 8566283881b7dfad3a3794477b8920a4
  page: PDF_5_性別不安有甚麼治療方法_-_醫院管理局_page.md
- name: PDF_CB420917-1819_-_立法會
  filename: PDF_CB420917-1819_-_立法會.pdf
  type: document
  format: PDF Document
  size: 1078150
  md5: 3bbeaf499e90e0822cde256f4774443e
  page: PDF_CB420917-1819_-_立法會_page.md
- name: PDF_同志QA_-_性別平等教育委員會
  filename: PDF_同志QA_-_性別平等教育委員會.pdf
  type: document
  format: PDF Document
  size: 26485212
  md5: ebfd539f235ed6b5fbff1d833d2308f8
  page: PDF_同志QA_-_性別平等教育委員會_page.md
- name: PDF_性別承認議題公眾諮詢FAQ1_-_立法會
  filename: PDF_性別承認議題公眾諮詢FAQ1_-_立法會.pdf
  type: document
  format: PDF Document
  size: 865822
  md5: ac3cc4a643b7a23dc13b826771c27248
  page: PDF_性別承認議題公眾諮詢FAQ1_-_立法會_page.md
- name: PDF_接受性別重置手術人仕的簡介_-_立法會
  filename: PDF_接受性別重置手術人仕的簡介_-_立法會.pdf
  type: document
  format: PDF Document
  size: 704833
  md5: 814a0f6c5aedeb3390fed093e6b3d6a2
  page: PDF_接受性別重置手術人仕的簡介_-_立法會_page.md
- name: PDF_新北市政府參加彩虹城市網絡RCN支持多元性別友善計畫
  filename: PDF_新北市政府參加彩虹城市網絡RCN支持多元性別友善計畫.pdf
  type: document
  format: PDF Document
  size: 555890
  md5: ac63290f41055a269a8c12ba200978e3
  page: PDF_新北市政府參加彩虹城市網絡RCN支持多元性別友善計畫_page.md
- name: PDF_行政院我國多元性別LGBTI者生活狀況調查_委託研究案辦理成果
  filename: PDF_行政院我國多元性別LGBTI者生活狀況調查_委託研究案辦理成果.pdf
  type: document
  format: PDF Document
  size: 1993104
  md5: 888fbb47fdad42cd67bba2c3ef93f66b
  page: PDF_行政院我國多元性別LGBTI者生活狀況調查_委託研究案辦理成果_page.md
- name: PDF_跨性別是泛指任何人的性別認同及或其性別表達
  filename: PDF_跨性別是泛指任何人的性別認同及或其性別表達.pdf
  type: document
  format: PDF Document
  size: 391903
  md5: 9dc5e41bfab24f330ffbb51c41f05204
  page: PDF_跨性別是泛指任何人的性別認同及或其性別表達_page.md
- name: PDF_跨性別者的日常生活_跨性別QA_大臺北跨性別友善資源_-_臺北市首座
  filename: PDF_跨性別者的日常生活_跨性別QA_大臺北跨性別友善資源_-_臺北市首座.pdf
  type: document
  format: PDF Document
  size: 2885483
  md5: cd8185b572c73ee6246293dcdc44378a
  page: PDF_跨性別者的日常生活_跨性別QA_大臺北跨性別友善資源_-_臺北市首座_page.md
- name: PDF_零拒絕的愛-尊重與包容多元的性別差異_-_高雄市政府
  filename: PDF_零拒絕的愛-尊重與包容多元的性別差異_-_高雄市政府.pdf
  type: document
  format: PDF Document
  size: 2149359
  md5: 90c755553ab37367cd98db5073cb7a1e
  page: PDF_零拒絕的愛-尊重與包容多元的性別差異_-_高雄市政府_page.md
- name: PDF_香港醫院管理局就性別不安所提供的治療
  filename: PDF_香港醫院管理局就性別不安所提供的治療.pdf
  type: document
  format: PDF Document
  size: 708870
  md5: c62ebf96918ddc1e0086db4b179f4226
  page: PDF_香港醫院管理局就性別不安所提供的治療_page.md
- name: 內政部研商性別變更認定及登記程序
  filename: 內政部研商性別變更認定及登記程序.pdf
  type: document
  format: PDF Document
  size: 409114
  md5: 457ae987a39f9fccbc96b2428f01362f
  page: 內政部研商性別變更認定及登記程序_page.md
- name: 反对國小性別平等教育內容_台湾
  filename: 反对國小性別平等教育內容_台湾.pdf
  type: document
  format: PDF Document
  size: 1331888
  md5: e53ecd69064261c155e45359de3b27ab
  page: 反对國小性別平等教育內容_台湾_page.md
- name: 各國跨性別登記制度_中华民国內政部委託研究報告
  filename: 各國跨性別登記制度_中华民国內政部委託研究報告.pdf
  type: document
  format: PDF Document
  size: 2019808
  md5: 8b0617cf0a6358de0cb4929aaf7b2d9d
  page: 各國跨性別登記制度_中华民国內政部委託研究報告_page.md
- name: 性別平等教育委員會_性平大學堂徵答題目
  filename: 性別平等教育委員會_性平大學堂徵答題目.pdf
  type: document
  format: PDF Document
  size: 173774
  md5: cd5eb20fe191bd0f0517aa1395852137
  page: 性別平等教育委員會_性平大學堂徵答題目_page.md
- name: 性別承認跨部門工作小組諮詢文件_香港
  filename: 性別承認跨部門工作小組諮詢文件_香港.pdf
  type: document
  format: PDF Document
  size: 4861655
  md5: ff2ce95a467f83433b0c1309ad7db74d
  page: 性別承認跨部門工作小組諮詢文件_香港_page.md
- name: 性別變更戶政法令研討及案例分享
  filename: 性別變更戶政法令研討及案例分享.pdf
  type: document
  format: PDF Document
  size: 100487
  md5: 3f060beb6bbe7d0033841cc4d0a50429
  page: 性別變更戶政法令研討及案例分享_page.md
- name: 澳门大学法医学教程进度（2015-2016学年度）
  filename: 澳门大学法医学教程进度（2015-2016学年度）.pdf
  type: document
  format: PDF Document
  size: 1237252
  md5: faf54d5ccf303fb371b6313b0313fa25
  page: 澳门大学法医学教程进度（2015-2016学年度）_page.md
- name: 臺北市政府教育局109年性別平等工作成果報告
  filename: 臺北市政府教育局109年性別平等工作成果報告.pdf
  type: document
  format: PDF Document
  size: 5667466
  md5: afbee4694bc07eb2152337b5fe58d15d
  page: 臺北市政府教育局109年性別平等工作成果報告_page.md
- name: 臺北榮民總醫院多元性別友善就醫環境作業指導書_2022
  filename: 臺北榮民總醫院多元性別友善就醫環境作業指導書_2022.pdf
  type: document
  format: PDF Document
  size: 198489
  md5: 66483fd36b17527ed8f698cdbda4c77a
  page: 臺北榮民總醫院多元性別友善就醫環境作業指導書_2022_page.md
- name: 臺南市政府民政局性別平等宣導報告
  filename: 臺南市政府民政局性別平等宣導報告.pdf
  type: document
  format: PDF Document
  size: 13346962
  md5: aca2a7e21cb7cd16c6b62e25c3b356ed
  page: 臺南市政府民政局性別平等宣導報告_page.md
- name: 苗栗縣性別平等業務成果報告
  filename: 苗栗縣性別平等業務成果報告.pdf
  type: document
  format: PDF Document
  size: 930772
  md5: dd4b817df10ce2f91dc1ac19e7aa47e6
  page: 苗栗縣性別平等業務成果報告_page.md
- name: 跨性别资源中心-港澳地区信息汇总
  filename: 跨性别资源中心-港澳地区信息汇总.pdf
  type: document
  format: PDF Document
  size: 4281256
  md5: e79a7204a124e22e2f11d1cd589c823a
  page: 跨性别资源中心-港澳地区信息汇总_page.md
- name: 香港性教育現狀與挑戰報告_2021
  filename: 香港性教育現狀與挑戰報告_2021.pdf
  type: document
  format: PDF Document
  size: 1385188
  md5: 396371f64bc55c6b3df3cfc468e3a6b0
  page: 香港性教育現狀與挑戰報告_2021_page.md
- name: 高雄市性別友善觀光報告_2023
  filename: 高雄市性別友善觀光報告_2023.pdf
  type: document
  format: PDF Document
  size: 3189052
  md5: 79ee86bc43e88becc0e2d3c7d6d3fa61
  page: 高雄市性別友善觀光報告_2023_page.md
subdirs: []
