name: 医院和医疗体系
description: 此目录收录了与跨性别相关的医院及医疗体系信息，例如医疗资源、医院政策及医疗经验分享等。这些资料可帮助跨性别者了解医疗服务的可获得性和具体体验。
curator: ''
source: ''
tags:
- 跨性别
- 医疗资源
- 医院信息
- 经验分享
- 医疗政策
license: ''
files:
- name: FtM超处方用药现状-国外正规药物
  filename: FtM超处方用药现状-国外正规药物.pdf
  type: document
  format: PDF Document
  size: 341703
  md5: 9d3b154ddb5dbf22300ed1833930d45a
  page: FtM超处方用药现状-国外正规药物_page.md
- name: MTF_流程
  filename: MTF_流程.pdf
  type: document
  format: PDF Document
  size: 340955
  md5: c437b0c98fc4847073c1008331d75278
  page: MTF_流程_page.md
- name: PDF_万邦德医药控股集团股份有限公司_-_启信宝
  filename: PDF_万邦德医药控股集团股份有限公司_-_启信宝.PDF
  type: document
  format: PDF Document
  size: 5015844
  md5: e13b2f9c273fb39daf5675ed1d718af4
  page: PDF_万邦德医药控股集团股份有限公司_-_启信宝_page.md
- name: PDF_十一酸睾酮软胶囊说明书
  filename: PDF_十一酸睾酮软胶囊说明书.pdf
  type: document
  format: PDF Document
  size: 2956937
  md5: d7f21d052f1ebd9a7fd9c465e2fd4e85
  page: PDF_十一酸睾酮软胶囊说明书_page.md
- name: PDF_双性恋变性及其他异常性取向者中有心理健康问题者的帮助_-_MindOut
  filename: PDF_双性恋变性及其他异常性取向者中有心理健康问题者的帮助_-_MindOut.pdf
  type: document
  format: PDF Document
  size: 203116
  md5: 4001dafdc2ef5d9eb17b415e8bdbaec8
  page: PDF_双性恋变性及其他异常性取向者中有心理健康问题者的帮助_-_MindOut_page.md
- name: PDF_心理健康与COVID-19
  filename: PDF_心理健康与COVID-19.pdf
  type: document
  format: PDF Document
  size: 548545
  md5: 7e73c8acc71d216f6e19e844f832a6f0
  page: PDF_心理健康与COVID-19_page.md
- name: PDF_心理健康宣传月职场_与新冠疫情
  filename: PDF_心理健康宣传月职场_与新冠疫情.pdf
  type: document
  format: PDF Document
  size: 5883234
  md5: acc6bc6bf3a7699d6adea89aa2ca742d
  page: PDF_心理健康宣传月职场_与新冠疫情_page.md
- name: PDF_雌二醇片雌二醇地屈孕酮片复合包装1_10mg_说明书pdf_-_Abbott
  filename: PDF_雌二醇片雌二醇地屈孕酮片复合包装1_10mg_说明书pdf_-_Abbott.pdf
  type: document
  format: PDF Document
  size: 6904495
  md5: 68614f7871fc06976586a42758c654c1
  page: PDF_雌二醇片雌二醇地屈孕酮片复合包装1_10mg_说明书pdf_-_Abbott_page.md
- name: PDF_雌二醇片雌二醇地屈孕酮片复合包装说明书_-_Abbott
  filename: PDF_雌二醇片雌二醇地屈孕酮片复合包装说明书_-_Abbott.pdf
  type: document
  format: PDF Document
  size: 7141095
  md5: 54568fbfc2f20d50e6bec2df2c2d3d48
  page: PDF_雌二醇片雌二醇地屈孕酮片复合包装说明书_-_Abbott_page.md
- name: 【ftm】关于激素、假药、药商的一切，纯干货！1
  filename: 【ftm】关于激素、假药、药商的一切，纯干货！1.docx
  type: document
  format: Microsoft Word Document (OpenXML)
  size: 4037217
  md5: 096bd675e51a91555979d1bead7f6d51
  page: 【ftm】关于激素、假药、药商的一切，纯干货！1_page.md
- name: 北京大学第三医院-_跨性别序列医疗
  filename: 北京大学第三医院-_跨性别序列医疗.pdf
  type: document
  format: PDF Document
  size: 38767279
  md5: 486808417a2edf2640e6e561c5050bc6
  page: 北京大学第三医院-_跨性别序列医疗_page.md
- name: 变性后欲望唤起
  filename: 变性后欲望唤起.txt
  type: document
  format: Plain Text
  size: 22285
  md5: 0af4e8740e57eabd64fd3a1e398ecb03
  page: 变性后欲望唤起_page.md
- name: 变性手术资料(1)
  filename: 变性手术资料(1).doc
  type: document
  format: Microsoft Word Document
  size: 37888
  md5: d2d09d69df973015a230757902ac5e27
  page: 变性手术资料(1)_page.md
- name: 常见假药
  filename: 常见假药.pdf
  type: document
  format: PDF Document
  size: 437436
  md5: c0434cec27aa1332729def38b10cec4c
  page: 常见假药_page.md
- name: 支持性别多样化儿童和跨性别青少年_-_Trans_Care_BC
  filename: 支持性别多样化儿童和跨性别青少年_-_Trans_Care_BC.pdf
  type: document
  format: PDF Document
  size: 1888623
  md5: 88507dfd456d29a7cfb144a150544ae4
  page: 支持性别多样化儿童和跨性别青少年_-_Trans_Care_BC_page.md
- name: 曼谷雨变性医生简介
  filename: 曼谷雨变性医生简介.docx
  type: document
  format: Microsoft Word Document (OpenXML)
  size: 1367600
  md5: fb5d4a384cc5a4221212cba29ccf6885
  page: 曼谷雨变性医生简介_page.md
- name: 曼谷雨变性医生简介
  filename: 曼谷雨变性医生简介.pdf
  type: document
  format: PDF Document
  size: 6991389
  md5: cb2d0195a6d2b1bc5840856bc55d9c90
  page: 曼谷雨变性医生简介_page.md
- name: 艾滋病防治社会组织大有作为
  filename: 艾滋病防治社会组织大有作为.pdf
  type: document
  format: PDF Document
  size: 4422301
  md5: 53650c3d14af253ba1911a3d0956130f
  page: 艾滋病防治社会组织大有作为_page.md
- name: 负责任的药物使用_-_PsychonautWiki
  filename: 负责任的药物使用_-_PsychonautWiki.pdf
  type: document
  format: PDF Document
  size: 1318991
  md5: d70149530855e157592626a49a847fc3
  page: 负责任的药物使用_-_PsychonautWiki_page.md
- name: 非歧视与沟通援助_Providence_St._Joseph_健康中心
  filename: 非歧视与沟通援助_Providence_St._Joseph_健康中心.pdf
  type: document
  format: PDF Document
  size: 481940
  md5: 86229cdb8c64c1296aec4976a98c7d94
  page: 非歧视与沟通援助_Providence_St._Joseph_健康中心_page.md
subdirs:
- 激素相关图片资料
