name: 医院和医疗体系
description: 此目录收录了与跨性别相关的医院及医疗体系信息，例如医疗资源、医院政策及医疗经验分享等。这些资料可帮助跨性别者了解医疗服务的可获得性和具体体验。
curator: ''
source: ''
tags:
- 跨性别
- 医疗资源
- 医院信息
- 经验分享
- 医疗政策
license: ''
files:
- name: 2022年青少年COVID-19疫苗接种登记表
  filename: 2022年青少年COVID-19疫苗接种登记表.pdf
  type: document
  format: PDF Document
  size: 176821
  md5: c921b1c75ba9974b1e33001364fed0c2
  page: 2022年青少年COVID-19疫苗接种登记表_page.md
- name: El_Dorado县健康教育课程
  filename: El_Dorado县健康教育课程.pdf
  type: document
  format: PDF Document
  size: 371692
  md5: cde722fdf287cfdbcc6dd8883ba55dc2
  page: El_Dorado县健康教育课程_page.md
- name: FtM超处方用药现状-国外正规药物
  filename: FtM超处方用药现状-国外正规药物.pdf
  type: document
  format: PDF Document
  size: 341703
  md5: 9d3b154ddb5dbf22300ed1833930d45a
  page: FtM超处方用药现状-国外正规药物_page.md
- name: MTF_流程
  filename: MTF_流程.pdf
  type: document
  format: PDF Document
  size: 340955
  md5: c437b0c98fc4847073c1008331d75278
  page: MTF_流程_page.md
- name: PDF_万邦德医药控股集团股份有限公司_-_启信宝
  filename: PDF_万邦德医药控股集团股份有限公司_-_启信宝.PDF
  type: document
  format: PDF Document
  size: 5015844
  md5: e13b2f9c273fb39daf5675ed1d718af4
  page: PDF_万邦德医药控股集团股份有限公司_-_启信宝_page.md
- name: PDF_十一酸睾酮软胶囊说明书
  filename: PDF_十一酸睾酮软胶囊说明书.pdf
  type: document
  format: PDF Document
  size: 2956937
  md5: d7f21d052f1ebd9a7fd9c465e2fd4e85
  page: PDF_十一酸睾酮软胶囊说明书_page.md
- name: PDF_双性恋变性及其他异常性取向者中有心理健康问题者的帮助_-_MindOut
  filename: PDF_双性恋变性及其他异常性取向者中有心理健康问题者的帮助_-_MindOut.pdf
  type: document
  format: PDF Document
  size: 203116
  md5: 4001dafdc2ef5d9eb17b415e8bdbaec8
  page: PDF_双性恋变性及其他异常性取向者中有心理健康问题者的帮助_-_MindOut_page.md
- name: PDF_心理健康与COVID-19
  filename: PDF_心理健康与COVID-19.pdf
  type: document
  format: PDF Document
  size: 548545
  md5: 7e73c8acc71d216f6e19e844f832a6f0
  page: PDF_心理健康与COVID-19_page.md
- name: PDF_心理健康宣传月职场_与新冠疫情
  filename: PDF_心理健康宣传月职场_与新冠疫情.pdf
  type: document
  format: PDF Document
  size: 5883234
  md5: acc6bc6bf3a7699d6adea89aa2ca742d
  page: PDF_心理健康宣传月职场_与新冠疫情_page.md
- name: PDF_雌二醇片雌二醇地屈孕酮片复合包装1_10mg_说明书pdf_-_Abbott
  filename: PDF_雌二醇片雌二醇地屈孕酮片复合包装1_10mg_说明书pdf_-_Abbott.pdf
  type: document
  format: PDF Document
  size: 6904495
  md5: 68614f7871fc06976586a42758c654c1
  page: PDF_雌二醇片雌二醇地屈孕酮片复合包装1_10mg_说明书pdf_-_Abbott_page.md
- name: PDF_雌二醇片雌二醇地屈孕酮片复合包装说明书_-_Abbott
  filename: PDF_雌二醇片雌二醇地屈孕酮片复合包装说明书_-_Abbott.pdf
  type: document
  format: PDF Document
  size: 7141095
  md5: 54568fbfc2f20d50e6bec2df2c2d3d48
  page: PDF_雌二醇片雌二醇地屈孕酮片复合包装说明书_-_Abbott_page.md
- name: 【ftm】关于激素、假药、药商的一切，纯干货！1
  filename: 【ftm】关于激素、假药、药商的一切，纯干货！1.docx
  type: document
  format: Microsoft Word Document (OpenXML)
  size: 4037217
  md5: 096bd675e51a91555979d1bead7f6d51
  page: 【ftm】关于激素、假药、药商的一切，纯干货！1_page.md
- name: 健康风险评估与会员资料_2023
  filename: 健康风险评估与会员资料_2023.pdf
  type: document
  format: PDF Document
  size: 338377
  md5: 09126b76944cc1a7898b4e9c85266a29
  page: 健康风险评估与会员资料_2023_page.md
- name: 北京大学第三医院-_跨性别序列医疗
  filename: 北京大学第三医院-_跨性别序列医疗.pdf
  type: document
  format: PDF Document
  size: 38767279
  md5: 486808417a2edf2640e6e561c5050bc6
  page: 北京大学第三医院-_跨性别序列医疗_page.md
- name: 北医三院“易性症”序列治疗就诊指南
  filename: 北医三院“易性症”序列治疗就诊指南.pdf
  type: document
  format: PDF Document
  size: 72415
  md5: 16a76cf0c8c7542f5eaed3cfaec6a6f9
  page: 北医三院“易性症”序列治疗就诊指南_page.md
- name: 北医三院易性症序列医疗团队
  filename: 北医三院易性症序列医疗团队.pdf
  type: document
  format: PDF Document
  size: 362403
  md5: 2d4d4bc79cff008c5062da0fec32eeed
  page: 北医三院易性症序列医疗团队_page.md
- name: 变性手术资料_1_
  filename: 变性手术资料_1_.doc
  type: document
  format: Microsoft Word Document
  size: 37888
  md5: d2d09d69df973015a230757902ac5e27
  page: 变性手术资料_1__page.md
- name: 家庭咨询服务会面记录
  filename: 家庭咨询服务会面记录.pdf
  type: document
  format: PDF Document
  size: 621762
  md5: 1d3dd295a95d10857642cef45e876aa6
  page: 家庭咨询服务会面记录_page.md
- name: 富德生命人寿终身护理保险产品说明书
  filename: 富德生命人寿终身护理保险产品说明书.pdf
  type: document
  format: PDF Document
  size: 316605
  md5: de7a0fa4c9ea0404984ff93471ba797f
  page: 富德生命人寿终身护理保险产品说明书_page.md
- name: 常见假药
  filename: 常见假药.pdf
  type: document
  format: PDF Document
  size: 437436
  md5: c0434cec27aa1332729def38b10cec4c
  page: 常见假药_page.md
- name: 患者登记表_2019年7月
  filename: 患者登记表_2019年7月.pdf
  type: document
  format: PDF Document
  size: 301382
  md5: 7dc3641bc16e1f9c1196e73b1bba102c
  page: 患者登记表_2019年7月_page.md
- name: 打造健康圣地亚哥LGBTQ+精神健康挑战报告
  filename: 打造健康圣地亚哥LGBTQ+精神健康挑战报告.pdf
  type: document
  format: PDF Document
  size: 690361
  md5: df40c67234d36522495936ddb402118c
  page: 打造健康圣地亚哥LGBTQ+精神健康挑战报告_page.md
- name: 支持性别多样化儿童和跨性别青少年_-_Trans_Care_BC
  filename: 支持性别多样化儿童和跨性别青少年_-_Trans_Care_BC.pdf
  type: document
  format: PDF Document
  size: 1888623
  md5: 88507dfd456d29a7cfb144a150544ae4
  page: 支持性别多样化儿童和跨性别青少年_-_Trans_Care_BC_page.md
- name: 曼谷雨变性医生简介
  filename: 曼谷雨变性医生简介.docx
  type: document
  format: Microsoft Word Document (OpenXML)
  size: 1367600
  md5: fb5d4a384cc5a4221212cba29ccf6885
  page: 曼谷雨变性医生简介_page.md
- name: 曼谷雨变性医生简介
  filename: 曼谷雨变性医生简介.pdf
  type: document
  format: PDF Document
  size: 6991389
  md5: cb2d0195a6d2b1bc5840856bc55d9c90
  page: 曼谷雨变性医生简介_page.md
- name: 省属公立医院医疗服务项目价格一览表
  filename: 省属公立医院医疗服务项目价格一览表.pdf
  type: document
  format: PDF Document
  size: 140339
  md5: d2ae97e1a2e9a37b3fab4f819f6d9905
  page: 省属公立医院医疗服务项目价格一览表_page.md
- name: 纽约健康医院LGBTQ+医疗中心宣传
  filename: 纽约健康医院LGBTQ+医疗中心宣传.pdf
  type: document
  format: PDF Document
  size: 3244310
  md5: 436ecf51bd037d02ef2e1e1536b9a70b
  page: 纽约健康医院LGBTQ+医疗中心宣传_page.md
- name: 艾滋病防治社会组织大有作为
  filename: 艾滋病防治社会组织大有作为.pdf
  type: document
  format: PDF Document
  size: 4422301
  md5: 53650c3d14af253ba1911a3d0956130f
  page: 艾滋病防治社会组织大有作为_page.md
- name: 负责任的药物使用_-_PsychonautWiki
  filename: 负责任的药物使用_-_PsychonautWiki.pdf
  type: document
  format: PDF Document
  size: 1318991
  md5: d70149530855e157592626a49a847fc3
  page: 负责任的药物使用_-_PsychonautWiki_page.md
- name: 非歧视与沟通援助_Providence_St._Joseph_健康中心
  filename: 非歧视与沟通援助_Providence_St._Joseph_健康中心.pdf
  type: document
  format: PDF Document
  size: 481940
  md5: 86229cdb8c64c1296aec4976a98c7d94
  page: 非歧视与沟通援助_Providence_St._Joseph_健康中心_page.md
subdirs:
- 激素相关图片资料
