name: 中国大陆
description: 这一目录包含了有关中国大陆的跨性别社群及非政府组织（NGO）的信息和资源，旨在为跨性别者提供一个互助与支持的平台。
curator: ''
source: ''
tags:
- 社群
- NGO
- 跨性别
- 中国大陆
- 支持
- 互助
license: ''
files:
- name: 2017秋季泰国法政大学交流心得
  filename: 2017秋季泰国法政大学交流心得.pdf
  type: document
  format: PDF Document
  size: 123399
  md5: 4cdb65d30c36ecc8d3a3a9b7624fa6ae
  page: 2017秋季泰国法政大学交流心得_page.md
- name: TERF问答
  filename: TERF问答.docx
  type: document
  format: Microsoft Word Document (OpenXML)
  size: 18424
  md5: 59704420f23c08dada7d4e148c0d0876
  page: TERF问答_page.md
- name: mtf.wiki_上面的导语被移除了
  filename: mtf.wiki_上面的导语被移除了.jpg
  type: image
  format: JPEG Image
  size: 118210
  md5: 242d646123fc3ef7ebc3183b6dea6c4a
  page: mtf.wiki_上面的导语被移除了.jpg
- name: 不知道哪里来的课件_第四章变态心理
  filename: 不知道哪里来的课件_第四章变态心理.pdf
  type: document
  format: PDF Document
  size: 746859
  md5: 1ccb435c8790fc6700e5405197929114
  page: 不知道哪里来的课件_第四章变态心理_page.md
- name: 关于在住院期间某位患者的言论情况整理
  filename: 关于在住院期间某位患者的言论情况整理.pdf
  type: document
  format: PDF Document
  size: 1583138
  md5: 424b25553fb65896b0b7b17fb0f04452
  page: 关于在住院期间某位患者的言论情况整理_page.md
- name: 劳动仲裁
  filename: 劳动仲裁.docx
  type: document
  format: Microsoft Word Document (OpenXML)
  size: 13202
  md5: 1b129fe0d1af1828a92ea6a9ac863cdc
  page: 劳动仲裁_page.md
- name: 向死去的志愿者致哀！
  filename: 向死去的志愿者致哀！.pdf
  type: document
  format: PDF Document
  size: 141481
  md5: df31d768e4c0b4dfd32f9f8a19a3d57d
  page: 向死去的志愿者致哀！_page.md
- name: 学历修改
  filename: 学历修改.pptx
  type: other
  format: Unknown Format
  size: 1558150
  md5: fa360f97425ac77b3a0256e2cd79ba71
  page: 学历修改.pptx
- name: 完全变装手册最后5章部分翻译
  filename: 完全变装手册最后5章部分翻译.pdf
  type: document
  format: PDF Document
  size: 612359
  md5: a9628752ee15481d1729762af49ed2fd
  page: 完全变装手册最后5章部分翻译_page.md
- name: 我们是跨别的孩子——献给一位故去的跨性别志愿者
  filename: 我们是跨别的孩子——献给一位故去的跨性别志愿者.doc
  type: document
  format: Microsoft Word Document
  size: 17920
  md5: bd1158c0c2a3246bed6049a55aac573f
  page: 我们是跨别的孩子——献给一位故去的跨性别志愿者_page.md
- name: 手术恢复
  filename: 手术恢复.jpg
  type: image
  format: JPEG Image
  size: 176832
  md5: 41b20b8ea98b641c71755ad9817cc0bd
  page: 手术恢复.jpg
- name: 授权委托书_民事自然人_
  filename: 授权委托书_民事自然人_.doc
  type: document
  format: Microsoft Word Document
  size: 28160
  md5: a193abce272b7a187fef486774644140
  page: 授权委托书_民事自然人__page.md
- name: 搞事情
  filename: 搞事情.pdf
  type: document
  format: PDF Document
  size: 2152009
  md5: 69514b89b8a81a1897550192051c09fd
  page: 搞事情_page.md
- name: 某个网友对ag的看法，原名《何为ag》
  filename: 某个网友对ag的看法，原名《何为ag》.doc
  type: document
  format: Microsoft Word Document
  size: 26112
  md5: 93a5057c995c2c719309c1ad32925e81
  page: 某个网友对ag的看法，原名《何为ag》_page.md
- name: 申请人身保护令
  filename: 申请人身保护令.docx
  type: document
  format: Microsoft Word Document (OpenXML)
  size: 18090
  md5: d91d02360d40460875fd771d3c1887ea
  page: 申请人身保护令_page.md
- name: 第四章变态心理教案授课时间
  filename: 第四章变态心理教案授课时间.pdf
  type: document
  format: PDF Document
  size: 229237
  md5: 2f69a22553f7be3b20062eddf60e9498
  page: 第四章变态心理教案授课时间_page.md
- name: 致函于贵院，关于一位患者在贵院西城院区住院期间的举报_北京友谊医院
  filename: 致函于贵院，关于一位患者在贵院西城院区住院期间的举报_北京友谊医院.pdf
  type: document
  format: PDF Document
  size: 2995594
  md5: 80357de3013a5d74362851ad6c7a0283
  page: 致函于贵院，关于一位患者在贵院西城院区住院期间的举报_北京友谊医院_page.md
- name: 跨性别基础关怀与心理支持
  filename: 跨性别基础关怀与心理支持.pdf
  type: document
  format: PDF Document
  size: 3224349
  md5: 3fc80bfc17156c1653dfdf96e96f54a0
  page: 跨性别基础关怀与心理支持_page.md
- name: 钱今凡回应网络对跨性别人士的谩骂
  filename: 钱今凡回应网络对跨性别人士的谩骂.doc
  type: document
  format: Microsoft Word Document
  size: 27648
  md5: f61107679f388d1bb947322ba366afc3
  page: 钱今凡回应网络对跨性别人士的谩骂_page.md
- name: 限制人身自由案_证据清单
  filename: 限制人身自由案_证据清单.docx
  type: document
  format: Microsoft Word Document (OpenXML)
  size: 12399
  md5: 40ec267f01023b7f58a09fe7b8dc72af
  page: 限制人身自由案_证据清单_page.md
subdirs: []
